language: python

python:
- '3.5'

install:
- pip install -r requirements-test.txt

script:
- tox

env:
  matrix:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110
  - TOXENV=flake8
  - TOXENV=coverage

after_success: coveralls

jobs:
  include:
    - stage: deploy
      env: TOXENV=py35-django110
      deploy:
        provider: pypi
        user: thorgate
        password:
          secure: >
            BONJP3X1ZzMrdCPtcXmEqvvfX00hzoXXi2d0jd2dq0lewG4ezgTUd/X8rdN3RHpIr4/p3n4Nn2FbxVdr3T0TrtiFo/8z/ABJnrCgx21cn/1MR
            9hmxYgYOUG1xqfz/oUXBuMBCBggVxDq5jEVQGeGMBll2zOw5PyHIzX92bbQV5Y=
        on:
          tags: true
          distributions: sdist bdist_wheel
          repo: thorgate/django-upthor

notifications:
  email: false
