language: python

python:
- '3.5'

install:
- pip install -r requirements-test.txt

script:
- tox

env:
  matrix:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110
  - TOXENV=flake8
  - TOXENV=coverage

after_success: coveralls

deploy:
  provider: pypi
  user: thorgate
  password:
    secure: >
      RG5CYr+x6BfSiQgkan2Y6NqeKpAIU4tcBdx7FxWrus320ewFRZjCb4g1l6QPTxzyIuekWQuwPp/RtS7VHU/sPq5jQX1vbxFGlydFuzLswwQuI
      tO8pmvaz6vLtSyS8XsIf2luON/I0QwUZ8klRiEKk9cyU8DDdX3fW+YVUuNpL20=
  on:
    # Warning: With this config, the package is released on pypi after the first matrix job succeeeds. This is currently fine
    #           since we shouldn't create tags before a successful build. Travis plans to add after_success callback in Q1/Q2 of
    #           2017. See https://github.com/travis-ci/travis-ci/issues/929 for more info.
    tags: true
    distributions: sdist bdist_wheel
    repo: thorgate/django-upthor

notifications:
  email: false
